#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"

# Image source
DOWNLOAD_URL_CHECKSUM="https://mirror-eu-de1.armbian.airframes.io/dl/aml-s9xx-box/archive/Armbian_23.5.1_Aml-s9xx-box_jammy_current_6.1.30.img.xz.sha"
DOWNLOAD_URL_IMAGE="https://mirror-eu-de1.armbian.airframes.io/dl/aml-s9xx-box/archive/Armbian_23.5.1_Aml-s9xx-box_jammy_current_6.1.30.img.xz"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE


export MODULES="base,deb_namserver,passwordless_sudo,pkgupgrade(network,klipper,node,is_req_preinstall,moonraker,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,dfu-util),password-for-sudo),postrename"
