#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"

# Image source
#DOWNLOAD_URL_CHECKSUM="https://martoo.myqnapcloud.com/share.cgi?ssid=daf89e3e1d8b4514af1d6719e29fa9c5"
DOWNLOAD_URL_IMAGE="https://martoo.myqnapcloud.com/share.cgi?ssid=b5acd12eeeb44fa585789da646e6c909&openfolder=forcedownload&ep=&_dc=1687784897878&fid=b5acd12eeeb44fa585789da646e6c909"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE


export MODULES="base,deb_namserver,passwordless_sudo,pkgupgrade(network,klipper,node,is_req_preinstall,moonraker,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,dfu-util),password-for-sudo),postrename"
